baseURL = 'https://zf2timo.github.io/'
languageCode = 'en-us'
title = 'zf2timo dev notes'
theme = "smigle"

[params]
    subtitle = "Some develop on the web"
    author = "zf2timo"
    brandIconFile = "images/zf2timo.png"

  [[params.social]]
  name = "GitHub"
  url = "https://github.com/zf2timo" 
  [[params.social]]
  name = "Twitter"
  url = "https://twitter.com/zf2timo"
